stages:
  - build
  - image-build
  - push
  - deploy

variables:
  RUNIMG: images

image: docker:cli
services:
  - docker:dind

docker-build:
  image: maven
  stage: build
  script:
    - mvn clean package
    - ls
  artifacts:
    paths:
      - "target"

docker-image-crt:
  variables:
    IMG: vimg
  stage: image-build
  script:
    - docker build -t $IMG:$CI_PIPELINE_ID .
    - docker $RUNIMG
    - mkdir demo
    - docker save $IMG > demo/vimg.tar
    - pwd
    - ls 
  artifacts:
    paths:
      - "demo"

docker-test:
  stage: test
  script:
    - docker load -i demo/vimg.tar
    - docker $RUNIMG
    - docker run -d -p 8081:8080 vimg:$CI_PIPELINE_ID
    - docker ps
docker-push:
  stage: push
  script:
    - docker load -i demo/vimg.tar
    - docker $RUNIMG
    - docker tag vimg:$CI_PIPELINE_ID anand2807/maven-war-repo:$CI_PIPELINE_ID
    - docker login -u $username_demorepo -p $password_demorepo
    - docker push anand2807/maven-war-repo:$CI_PIPELINE_ID
    - docker $RUNIMG
    

docker-deploy:
  stage: deploy
  image: ubuntu
  before_script:
    - apt update && apt install git -y
    - apt install sed -y
  script:
    - |
      sed -i "s|image:.*|image: anand2807/maven-war-repo:$CI_PIPELINE_ID|" kubernetes/java_maven_deploy.yaml
    - git config --global user.name "ananthselvam956"
    - git config --global user.email "ananthselvam956@gmail.com"
    - git remote set-url origin "https://oauth2:$token@gitlab.com/ananthselvam956/vprofile-java-maven.git"
    - git remote -v
    - git checkout -B main
    - git add kubernetes/java_maven_deploy.yaml
    - git commit -m "Image tag has been changed $CI_PIPELINE_ID [skip ci]"
    - git push origin main

  


