apiVersion: v1
kind: Secret
metadata:
  name: mvn-sec
type: Kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIllXNWhibVF5T0RBM09tUmphM0pmY0dGMFgzaExhRFZ6Y1RoamRtMUtlR2xEYmtkTVZreDFPRjlJYTA1SFZRPT0iCgkJfQoJfQp9
